apiVersion: checker.looty.com/v1
kind: Checker
metadata:
  name: checker3
  namespace: default
spec:
  questRef: "3"
  validation: |
    #!/bin/bash

    storage=$(kubectl get persistentvolume/pv-three -n default -o jsonpath='{.spec.capacity.storage}')
    hostPath=$(kubectl get persistentvolume/pv-three -n default -o jsonpath='{.spec.hostPath.path}')

    if [ "$storage" == "1Gi" ] && [ "$hostPath" == "/path/to/file" ]; then
      exit 0
    fi

    exit 1
