local_resource(
    'delete db',
    cmd='rm project.db',
    trigger_mode=TRIGGER_MODE_MANUAL,
    labels=["backend"],
)

local_resource(
    'build & run',
    cmd='go build .',
    serve_cmd='./kubeground',
    deps=["go.mod", "go.sum"],
    labels=["backend"],
)

local_resource(
    'go test',
    cmd='go test .',
    deps=["."],
    ignore=["project.db"],
    labels=["backend"]
)