apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: checkers.checker.looty.com
spec:
  group: checker.looty.com
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                questRef:
                  type: string
                  default: ""
                validation:
                  type: string
                  default: ""
      additionalPrinterColumns:
        - name: QuestRef
          type: string
          description: The quest reference of the checker
          jsonPath: .spec.questRef
        - name: Validation
          type: string
          description: The quest validation commands of the checker
          jsonPath: .spec.validation
  scope: Namespaced
  names:
    kind: Checker
    plural: checkers
    singular: checker
    shortNames:
      - checkers
      - c
