apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "quest-operator.fullname" . }}-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "quest-operator.fullname" . }}-role-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "quest-operator.serviceAccountName" . }}
    namespace: {{ include "quest-operator.namespace" . }}
