apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeground.fullname" . }}
  namespace: {{ include "kubeground.namespace" . }}
  labels:
    {{- include "kubeground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubeground.selectorLabels" . | nindent 4 }}
