apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-provider
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-provider
  namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-provider
    namespace: crossplane-system
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: helm-provider
  namespace: crossplane-system
spec:
  serviceAccountName: helm-provider
  args:
    - "--debug"
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: helm-provider
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
  controllerConfigRef:
    name: helm-provider
